"""new_fields

Revision ID: 453b8f70e1ad
Revises: a7aea7f27c3b
Create Date: 2025-12-10 19:24:18.904696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '453b8f70e1ad'
down_revision: Union[str, None] = 'a7aea7f27c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('educations', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('website', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'website')
    op.drop_column('educations', 'description')
    # ### end Alembic commands ###
