"""split_name_field

Revision ID: a7aea7f27c3b
Revises: 41fb176a1ab7
Create Date: 2025-12-10 14:04:12.101932

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7aea7f27c3b"
down_revision: str | None = "41fb176a1ab7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("first_name", sa.String(), nullable=False, server_default="")
    )
    op.add_column(
        "users", sa.Column("last_name", sa.String(), nullable=False, server_default="")
    )
    op.drop_column("users", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.VARCHAR(), nullable=False))
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
