from typing import Optional
from pydantic import BaseModel, Field

class JobSearchCriteria(BaseModel):
    keywords: Optional[str] = Field(None, alias="motsCles", description="Mots-clés de recherche")
    location: Optional[str] = Field(None, description="Code INSEE, code postal ou nom de la commune")
    distance: Optional[int] = Field(None, description="Rayon de recherche en km")
    departement: Optional[str] = Field(None, description="Code département (ex: 33, 75)")
    commune: Optional[str] = Field(None, description="Code INSEE commune")
    region: Optional[str] = Field(None, description="Code région")
    paysContinent: Optional[str] = Field(None, description="Code pays ou continent")
    typeContrat: Optional[str] = Field(None, description="Type de contrat (ex: CDI, CDD)")
    natureContrat: Optional[str] = Field(None, description="Nature de contrat (ex: E1)")
    experience: Optional[str] = Field(None, description="Niveau d'expérience (1: <1 an, 2: 1-3 ans, 3: >3 ans)")
    experienceExigence: Optional[str] = Field(None, description="D (débutant), S (souhaitée), E (exigée)")
    domaine: Optional[str] = Field(None, description="Domaine métier")
    grandDomaine: Optional[str] = Field(None, description="Grand domaine (ex: M18 Informatique)")
    theme: Optional[str] = Field(None, description="Thème ROME")
    appellation: Optional[str] = Field(None, description="Code appellation ROME")
    codeROME: Optional[str] = Field(None, description="Code ROME")
    secteurActivite: Optional[str] = Field(None, description="Division NAF (2 chiffres)")
    codeNAF: Optional[str] = Field(None, description="Code NAF complet")
    entrepriseAdaptee: Optional[bool] = Field(None, alias="entreprisesAdaptees", description="Entreprise adaptée")
    employeurHandiEngage: Optional[bool] = Field(None, alias="employeursHandiEngages", description="Employeur engagé handicap")
    accesTravailleurHandicape: Optional[bool] = Field(None, description="Accessible TH")
    offresMRS: Optional[bool] = Field(None, description="Recrutement par simulation")
    offresManqueCandidats: Optional[bool] = Field(None, description="Offres difficiles à pourvoir")
    tempsPlein: Optional[bool] = Field(None, description="Temps plein")
    dureeHebdo: Optional[str] = Field(None, description="1 (temps plein), 2 (temps partiel)")
    dureeHebdoMin: Optional[str] = Field(None, description="Durée hebdo min (HHMM)")
    dureeHebdoMax: Optional[str] = Field(None, description="Durée hebdo max (HHMM)")
    dureeContratMin: Optional[str] = Field(None, description="Durée contrat min (mois)")
    dureeContratMax: Optional[str] = Field(None, description="Durée contrat max (mois)")
    salaireMin: Optional[str] = Field(None, description="Salaire minimum")
    periodeSalaire: Optional[str] = Field(None, description="M (mensuel), A (annuel), H (horaire), C (cachet)")
    permis: Optional[str] = Field(None, description="Permis demandé")
    niveauFormation: Optional[str] = Field(None, description="Niveau formation (ex: NV3)")
    qualification: Optional[str] = Field(None, description="0 (non-cadre), 9 (cadre)")
    publieeDepuis: Optional[int] = Field(None, description="Publiée depuis X jours")
    minCreationDate: Optional[str] = Field(None, description="Date min création (ISO)")
    maxCreationDate: Optional[str] = Field(None, description="Date max création (ISO)")
    partenaires: Optional[str] = Field(None, description="Codes partenaires")
    modeSelectionPartenaires: Optional[str] = Field(None, description="INCLUS ou EXCLU")
    origineOffre: Optional[int] = Field(None, description="1 (France Travail), 2 (Partenaire)")
    inclureLimitrophes: Optional[bool] = Field(None, description="Inclure départements limitrophes")
    sort: Optional[int] = Field(None, description="0 (Pertinence), 1 (Date), 2 (Distance)")
    range_param: str = Field("0-49", alias="range", description="Pagination (ex: 0-49)")

    class Config:
        populate_by_name = True
